# Installing R Packages for graph
install.packages("maps")
install.packages("geosphere")
#loading in package
library("maps")
library("geosphere")
#Creating United States Map
map("world")
xlim <- c(-171.738281, -56.601563)
ylim <- c(12.039321, 71.856229)
#Shrinking Map to focus on the United States
map("world", col="#f2f2f2", fill=TRUE, bg="white", lwd=0.05, xlim=xlim, ylim=ylim)
# Reading in CSV with Flight Data
airports <- read.csv("http://datasets.flowingdata.com/tuts/maparcs/airports.csv", header=TRUE)
flights <- read.csv("http://datasets.flowingdata.com/tuts/maparcs/flights.csv", header=TRUE, as.is=TRUE)
# Mapping All flight routes
fsub <- flights
for (j in 1:length(fsub$airline)) {
  air1 <- airports[airports$iata == fsub[j,]$airport1,]
  air2 <- airports[airports$iata == fsub[j,]$airport2,]
  
  inter <- gcIntermediate(c(air1[1,]$long, air1[1,]$lat), c(air2[1,]$long, air2[1,]$lat), n=100, addStartEnd=TRUE)
  
  lines(inter, col="white", lwd=0.8)
}
# Mapping Flight Routes by Carrier
# Unique carriers
carriers <- unique(flights$airline)

# Color
pal <- colorRampPalette(c("lightblue1", "deepskyblue", "lightgoldenrod1"))
colors <- pal(100)

for (i in 1:length(carriers)) {
  
  jpeg(paste("carrier", carriers[i], ".jpg", sep=""), width=480, height=480)
  map("world", col="#191919", fill=TRUE, bg="white", lwd=0.05, xlim=xlim, ylim=ylim)
  fsub <- flights[flights$airline == carriers[i],]
  fsub <- fsub[order(fsub$cnt),]
  maxcnt <- max(fsub$cnt)
  for (j in 1:length(fsub$airline)) {
    air1 <- airports[airports$iata == fsub[j,]$airport1,]
    air2 <- airports[airports$iata == fsub[j,]$airport2,]
    
    inter <- gcIntermediate(c(air1[1,]$long, air1[1,]$lat), c(air2[1,]$long, air2[1,]$lat), n=100, addStartEnd=TRUE)
    colindex <- round( (fsub[j,]$cnt / maxcnt) * length(colors) )
    
    lines(inter, col=colors[colindex], lwd=0.6)
  }
  
  dev.off()
}